/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appManageRouteImport } from './routes/(app)/manage'
import { Route as appProfileProfileRouteImport } from './routes/(app)/profile/profile'
import { Route as appProductIdRouteImport } from './routes/(app)/product/$id'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
})
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
})
const appManageRoute = appManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => appRouteRoute,
})
const appProfileProfileRoute = appProfileProfileRouteImport.update({
  id: '/profile/profile',
  path: '/profile/profile',
  getParentRoute: () => appRouteRoute,
})
const appProductIdRoute = appProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => appRouteRoute,
})

const appRouteRouteChildren = {
  appManageRoute: appManageRoute,
  appIndexRoute: appIndexRoute,
  appProductIdRoute: appProductIdRoute,
  appProfileProfileRoute: appProfileProfileRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
